server:
  port: 8080
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  jackson:
    date-format: yyyy/MM/dd HH:mm
    time-zone: Asia/Seoul
  profiles:
    active: local # 기본 프로파일 (로컬 환경을 기본으로 설정)